MySite_DJ4E_Project/mysite/ads/urls.py
from django.urls import path

from . import views

app_name = 'ads'
urlpatterns = [
    # ex: /ads/
    path('', views.AdListView.as_view(), name='index'),
    # ex: /ads/detail/2161
    path('detail/<int:pk>', views.AdDetailView.as_view(), name='ad detail'),
    # ex: /ads/create
    path('create', views.AdCreateView.as_view(), name='ad create'),
    # ex: /ads/update/2161
    path('update/<int:pk>', views.AdUpdateView.as_view(), name='ad update'),
    # ex: /ads/delete/2161
    path('delete/<int:pk>', views.AdDeleteView.as_view(), name='ad delete'),
    # Ad File Stream
    path('ad_picture/<int:pk>', views.stream_file, name='ad picture'),
    # ex: /ads/2161/comment
    path('<int:pk>/comment', views.CommentCreateView.as_view(), name='ad comment create'),
    # ex: /ads/comment/2161/delete
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='ad comment delete'),
    # ex: /ads/favorite/2161
    path('<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad favorite'),
    # ex: /ads/unfavorite/2161
    path('unfavorite/<int:pk>', views.DeleteFavoriteView.as_view(), name='ad unfavorite'),
    ]

MySite_DJ4E_Project/mysite/autos/urls.py
from django.urls import path

from . import views

app_name = 'autos'
urlpatterns = [
    # ex: /autos/
    path('', views.AutoIndex.as_view(), name='index'),
    # ex: /autos/auto/create
    path('auto/create/', views.AutoCreate.as_view(), name='auto create'),
    # ex: /autos/auto/update/3
    path('auto/update/<int:pk>/', views.AutoUpdate.as_view(), name='auto update'),
    # ex: /autos/auto/delete/5
    path('auto/delete/<int:pk>/', views.AutoDelete.as_view(), name='auto delete'),
    # ex: /autos/make
    path('make', views.MakeList.as_view(), name='make list'),
    # ex: /autos/make/create
    path('make/create/', views.MakeCreate.as_view(), name='make create'),
    # ex: /autos/make/update/3
    path('make/update/<int:pk>/', views.MakeUpdate.as_view(), name='make update'),
    # ex: /autos/make/delete/5
    path('make/delete/<int:pk>/', views.MakeDelete.as_view(), name='make delete'),
]

MySite_DJ4E_Project/mysite/cats/urls.py
from django.urls import path

from . import views

app_name = 'cats'
urlpatterns = [
    # ex: /cats/
    path('', views.CatIndex.as_view(), name='index'),
    # ex: /cats/cat/create
    path('cat/create', views.CatCreate.as_view(), name='cat create'),
    # ex: /cats/cat/update/2161
    path('cat/update/<int:pk>', views.CatUpdate.as_view(), name='cat update'),
    # ex: /cats/cat/delete/2161
    path('cat/delete/<int:pk>', views.CatDelete.as_view(), name='cat delete'),
    # ex: /cats/breeds
    path('breeds/', views.BreedList.as_view(), name='breed list'),
    # ex: /cats/breed/create
    path('breed/create', views.BreedCreate.as_view(), name='breed create'),
    # ex: /cats/breed/update/2161
    path('breed/update/<int:pk>', views.BreedUpdate.as_view(), name='breed update'),
    # ex: /cats/breed/delete/2161
    path('breed/delete/<int:pk>', views.BreedDelete.as_view(), name='breed delete')
    ]

MySite_DJ4E_Project/mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view(), name="site root"),
]

MySite_DJ4E_Project/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /polls/owner/
    path('owner/', views.owner.as_view(), name='owner'),
]

MySite_DJ4E_Project/mysite/home/models.py
from django.db import models

# Create your models here.

MySite_DJ4E_Project/mysite/home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations


class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

MySite_DJ4E_Project/mysite/home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="a62aade1e0954398c32f6f090f50ee1b">

<meta name="dj4e-code" content="42164103517674">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2021-11-11">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

MySite_DJ4E_Project/mysite/home/templates/base_bootstrap_old.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="93f19dbc4426f203a274642a804f36e8">

<meta name="dj4e-code" content="42164103517674">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2021-11-11">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

MySite_DJ4E_Project/mysite/home/templates/base_bootstrap_quartz.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="93f19dbc4426f203a274642a804f36e8">

<meta name="dj4e-code" content="42164103517674">

<link href="https://bootswatch.com/5/quartz/bootstrap.min.css"
    rel="stylesheet"
    crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2021-11-11">

{% block head %} {% endblock %}

</head>
<body>
{% block navbar %} {% endblock %}
<div class="container">
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

MySite_DJ4E_Project/mysite/home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'ads:index' as ads %}
      <li {% if ads in request.get_full_path %}class="active"{% endif %}>
          <a href="{% url 'ads:index' %}">Ads</a></li>
    </ul>
    <ul class="nav navbar-nav">
      {% url 'autos:index' as autos %}
      <li {% if autos in request.get_full_path %}class="active"{% endif %}>
          <a href="{% url 'autos:index' %}">Autos</a></li>
    </ul>
    <ul class="nav navbar-nav">
      {% url 'cats:index' as cats %}
      <li {% if cats in request.get_full_path %}class="active"{% endif %}>
          <a href="{% url 'cats:index' %}">Cats</a></li>
    </ul>
    <ul class="nav navbar-nav">
      {% url 'polls:index' as polls %}
      <li {% if polls in request.get_full_path %}class="active"{% endif %}>
          <a href="{% url 'polls:index' %}">Polls</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        {% if ads in request.get_full_path %}
        <li>
        <a href="{% url 'ads:ad create' %}">Create Ad</a>
        </li>
        {% endif %}
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'ads:index' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'ads:index' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

MySite_DJ4E_Project/mysite/home/templates/base_menu_old.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'ads:index' as ads %}
      <li {% if ads in request.get_full_path %}class="active"{% endif %}>
          <a href="{% url 'ads:index' %}">Ads</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'snippets:api-root' %}">Snippet-API</a></li>
    </ul>
    <ul class="nav navbar-nav">
      {% url 'autos:index' as autos %}
      <li {% if autos in request.get_full_path %}class="active"{% endif %}>
          <a href="{% url 'autos:index' %}">Autos</a></li>
    </ul>
    <ul class="nav navbar-nav">
      {% url 'cats:index' as cats %}
      <li {% if cats in request.get_full_path %}class="active"{% endif %}>
          <a href="{% url 'cats:index' %}">Cats</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'polls:index' %}">Polls</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        {% if ads in request.get_full_path %}
        <li>
        <a href="{% url 'ads:ad create' %}">Create Ad</a>
        </li>
        {% endif %}
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'admin:index' %}">Admin Panel</a></li>
                <li><a href="{% url 'logout' %}?next={% url 'ads:index' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'ads:index' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

MySite_DJ4E_Project/mysite/home/templates/base_menu_quartz.html
{% extends "base_bootstrap_quartz.html" %}
{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-expand-xl navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/static/logo.png" alt="" width="175" class="d-inline-block align-text-top"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mx-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'api:api-root' %}">API Root</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">API List</a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'api:ad-list' %}">Ads API</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'api:snippet-list' %}">Snippet API</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'api:user-list' %}">User API</a></li>
          </ul>
        </li>
        <li class="nav-item">
        {% url 'ads:index' as ads %}
          <a {% if ads in request.get_full_path %}class="nav-link active"{% else %}class="nav-link"{% endif %} aria-current="page" href="{% url 'ads:index' %}">Ads</a>
        </li>
        <li class="nav-item">
        {% url 'autos:index' as autos %}
          <a {% if autos in request.get_full_path %}class="nav-link active"{% else %}class="nav-link"{% endif %} aria-current="page" href="{% url 'autos:index' %}">Autos</a>
        </li>
        <li class="nav-item">
        {% url 'cats:index' as cats %}
          <a {% if cats in request.get_full_path %}class="nav-link active"{% else %}class="nav-link"{% endif %} aria-current="page" href="{% url 'cats:index' %}">Cats</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:index' %}">Polls</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto mb-2 mb-md-0">
        {% if user.is_authenticated %}
        {% if ads in request.get_full_path %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ads:ad create' %}">Create Ad</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img style="width: 28px;" src="{{ user|gravatar:60 }}"/>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Panel</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'site root' %}">Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}?next={% url 'site root' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

{% endblock %}